name: Make Android APK and AAB

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Unzip the App
        run: |
          unzip *.zip -d myapp
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Convert to Android
        run: |
          cd myapp
          npm install
          npm install @capacitor/cli @capacitor/android @capacitor-community/admob @capacitor/assets
          npx cap add android
          
          # Fixes
          sed -i 's|</application>|<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-7377091766113250~6802900116"/>\n    </application>|g' android/app/src/main/AndroidManifest.xml
          find www -type f \( -name "*.html" -o -name "*.js" \) -exec sed -i 's/await AdMob.prepareInterstitial/await AdMob.initialize(); await AdMob.prepareInterstitial/g' {} +
          
          # Status bar fix
          sed -i 's|<item name="android:windowFullscreen">true</item>|<item name="android:windowFullscreen">false</item>|g' android/app/src/main/res/values/styles.xml || true
          
          # Copy Firebase File
          cp ../google-services.json android/app/ || true
          
          npx cap sync android

      - name: Build App & Extract SHA-1 Key
        run: |
          cd myapp/android
          chmod +x gradlew
          ./gradlew assembleDebug
          ./gradlew bundleDebug
          ./gradlew signingReport > ../../sha1-report.txt

      - name: Provide App Files
        uses: actions/upload-artifact@v4
        with:
          name: SSC-Desk-App-Files
          path: |
            myapp/android/app/build/outputs/apk/debug/app-debug.apk
            myapp/android/app/build/outputs/bundle/debug/app-debug.aab
            sha1-report.txt
